projetosMessage = 'Simpfique (-s)'
massaMessage = '-Produtos (-pro) Parceiros (-par)'
ambienteBancoMessage = 'Desenvolvimento (-d) Homologação (-h)'
preenchimentoMessage= 'Todos campos opcionais (-op) Campos obrigatórios (-o)'
opcaoInvalidaMessage = 'não existe. Por favor, tente novamente.'
confirmarMessage = 'Opção invalida de confirmação'
